//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_CHICKEN1                    158
#define IDB_CHICKEN2                    160
#define IDB_CHICKEN3                    161
#define IDB_BITMAP3                     162
#define IDB_CHICKEN4                    162
#define IDB_CHICKENRIGHT                171
#define IDB_CHICKENLEFT                 172
#define IDB_BITMAP4                     177
#define IDB_CHICKENRIGHT2               177
#define IDB_GREEN                       178
#define IDB_BLUE                        179
#define IDB_BITMAP5                     180
#define IDB_YELLOW                      180
#define IDB_Bomb1                       182
#define IDB_Stage1_1                    184
#define IDB_Stage1_2                    186
#define IDB_Stage1_3                    190
#define IDB_Stage1                      194
#define IDB_Bomb2                       195
#define IDB_Bomb3                       196
#define IDB_BITMAP6                     197
#define IDB_Bombfire                    197
#define IDB_start0                      198
#define IDB_start1                      199
#define IDB_start2                      200
#define IDB_start3                      201
#define IDB_loading1                    202
#define IDB_GEM                         204
#define IDB_HEART                       205
#define IDB_GEMLEFT                     207
#define IDB_ZERO                        208
#define IDB_ONE                         209
#define IDB_TWO                         210
#define IDB_THREE                       211
#define IDB_FOUR                        212
#define IDB_FIVE                        213
#define IDB_SIX                         214
#define IDB_SEVEN                       215
#define IDB_EIGHT                       216
#define IDB_NINE                        217
#define IDB_BUTTON                      218
#define IDB_BUTTON_LEFT                 219
#define IDB_BUTTON_RIGHT                220
#define IDB_BUTTON_DOWN                 221
#define IDB_BITMAP7                     222
#define IDB_DOOR_TYPE_1                 222
#define IDB_doorType2                   224
#define IDB_DOOR_TYPE_2                 224
#define IDB_WOOD_DOOR                   225
#define IDB_TREASURE                    226
#define IDB_ROCK                        227
#define IDB_EMPTY_HEART                 228
#define IDB_GAMEOVER                    229
#define IDB_ENEMY_01_LEFT               230
#define IDB_ENEMY_01_RIGHT              231
#define IDB_CHANGE_HEART_MAP            232
#define IDB_ENEMY_01_RIGHT_2            233
#define IDB_ENEMY_01_LEFT_2             234
#define IDB_ENEMY_02_01                 235
#define IDB_ENEMY_02_02                 236
#define IDB_ENEMY_03_01                 237
#define IDB_ENEMY_03_02                 238
#define IDB_ENEMY_04_01                 239
#define IDB_ENEMY_04_02                 240
#define IDB_BAT_LEFT_1                  241
#define IDB_BAT_LEFT_2                  242
#define IDB_BAT_RIGHT_1                 243
#define IDB_BAT_RIGHT_2                 244
#define IDB_Stage2                      245
#define IDB_ROCK2                       246
#define IDB_ROCK3                       247
#define IDB_ROCK4                       248
#define IDB_ROCK5                       249
#define IDB_HAMMER1                     250
#define IDB_HAMMER2                     251
#define IDB_HAMMER3                     252
#define IDB_MENU1_1                     253
#define IDB_MENU1_2                     254
#define IDB_MENU1_3                     255
#define IDB_MENU2_1                     256
#define IDB_MENU2_2                     257
#define IDB_MENU2_3                     258
#define IDB_MENU3_1                     259
#define IDB_MENU3_2                     260
#define IDB_MENU3_3                     261
#define IDB_Stage3                      262
#define IDB_CANTPUTBOMB                 263
#define IDB_CARD                        264
#define IDB_ABOUT                       265
#define IDB_operation                   266
#define IDB_operation_shiw              267
#define IDB_operation_show              267
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        268
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
